# Generated by Django 4.1.7 on 2023-03-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corkboard', '0002_user_fifth_dish_user_first_dish_user_fourth_dish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
